/* Generated By:JavaCC: Do not edit this line. JavaCCParserConstants.java */
package jminusminus;

public interface JavaCCParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int ABSTRACT = 7;
  int BOOLEAN = 8;
  int CHAR = 9;
  int CLASS = 10;
  int ELSE = 11;
  int EXTENDS = 12;
  int FALSE = 13;
  int IF = 14;
  int IMPORT = 15;
  int INSTANCEOF = 16;
  int INT = 17;
  int NEW = 18;
  int NULL = 19;
  int PACKAGE = 20;
  int PRIVATE = 21;
  int PROTECTED = 22;
  int PUBLIC = 23;
  int RETURN = 24;
  int STATIC = 25;
  int SUPER = 26;
  int THIS = 27;
  int TRUE = 28;
  int VOID = 29;
  int WHILE = 30;
  int DOUBLE = 31;
  int BREAK = 32;
  int BYTE = 33;
  int CASE = 34;
  int CATCH = 35;
  int CONST = 36;
  int CONTINUE = 37;
  int DO = 38;
  int FINALLY = 39;
  int FLOAT = 40;
  int INTERFACE = 41;
  int FOR = 42;
  int LONG = 43;
  int GOTO = 44;
  int NATIVE = 45;
  int IMPLEMENTS = 46;
  int STRICTFP = 47;
  int SWITCH = 48;
  int SYNCHRONIZED = 49;
  int THROW = 50;
  int THROWS = 51;
  int TRANSIENT = 52;
  int TRY = 53;
  int VOLATILE = 54;
  int PLUS = 55;
  int ASSIGN = 56;
  int DEC = 57;
  int EQUAL = 58;
  int GT = 59;
  int INC = 60;
  int LAND = 61;
  int LE = 62;
  int LNOT = 63;
  int MINUS = 64;
  int PLUS_ASSIGN = 65;
  int STAR = 66;
  int DIV = 67;
  int REM = 68;
  int SHL = 69;
  int SHR = 70;
  int UCOM = 71;
  int BOR = 72;
  int URSHIFT = 73;
  int AND = 74;
  int XOR = 75;
  int QMARK = 76;
  int NOTEQ = 77;
  int DIV_ASSIGN = 78;
  int SUB_ASSIGN = 79;
  int MULTI_ASSIGN = 80;
  int MOD_ASSIGN = 81;
  int RIGHS_ASSIGN = 82;
  int USHL_ASSIGN = 83;
  int USHR_ASSIGN = 84;
  int GE = 85;
  int LT = 86;
  int XOR_ASSIGN = 87;
  int BOR_ASSIGN = 88;
  int LOR = 89;
  int AND_ASSIGN = 90;
  int LPAREN = 91;
  int RPAREN = 92;
  int LCURLY = 93;
  int RCURLY = 94;
  int LBRACK = 95;
  int RBRACK = 96;
  int SEMI = 97;
  int COMMA = 98;
  int DOT = 99;
  int COLON = 100;
  int IDENTIFIER = 101;
  int LETTER = 102;
  int DIGIT = 103;
  int NON_ZERO_DIGIT = 104;
  int INT_LITERAL = 105;
  int CHAR_LITERAL = 106;
  int STRING_LITERAL = 107;
  int ESC = 108;
  int DOUBLE_LITERAL = 109;
  int ERROR = 110;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "\"abstract\"",
    "\"boolean\"",
    "\"char\"",
    "\"class\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"if\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"static\"",
    "\"super\"",
    "\"this\"",
    "\"true\"",
    "\"void\"",
    "\"while\"",
    "\"double\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"const\"",
    "\"continue\"",
    "\"do\"",
    "\"finally\"",
    "\"float\"",
    "\"interface\"",
    "\"for\"",
    "\"long\"",
    "\"goto\"",
    "\"native\"",
    "\"implements\"",
    "\"strictfp\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"try\"",
    "\"volatile\"",
    "\"+\"",
    "\"=\"",
    "\"--\"",
    "\"==\"",
    "\">\"",
    "\"++\"",
    "\"&&\"",
    "\"<=\"",
    "\"!\"",
    "\"-\"",
    "\"+=\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\"~\"",
    "\"|\"",
    "\">>>\"",
    "\"&\"",
    "\"^\"",
    "\"?\"",
    "\"!=\"",
    "\"/=\"",
    "\"-=\"",
    "\"*=\"",
    "\"%=\"",
    "\">>=\"",
    "\"<<=\"",
    "\">>>=\"",
    "\">=\"",
    "\"<\"",
    "\"^=\"",
    "\"|=\"",
    "\"||\"",
    "\"&=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<NON_ZERO_DIGIT>",
    "<INT_LITERAL>",
    "<CHAR_LITERAL>",
    "<STRING_LITERAL>",
    "<ESC>",
    "<DOUBLE_LITERAL>",
    "<ERROR>",
  };

}
